### ISSUE TITLE
File not found

### ISSUE THREAD

**Issue by DevLucem** [ByteXcite/versign#5] opened 2018-09-22 20:11 UTC
https://github.com/ByteXcite/versign/blob/23660661019309986d76357e09d46f12a0441164/versign-web/src/util/Database.php#L22

This file is not included in the repository. Where can we get it?

**Comment by saifkhichi96** [comment] 2021-06-27 11:01
Duplicate of #4

**Closed as completed by saifkhichi96** 2021-06-27 11:01 UTC
